# Autogenerated wrapper script for CLN_jll for aarch64-apple-darwin
export cln_pi, libcln

using GMP_jll
JLLWrappers.@generate_wrapper_header("CLN")
JLLWrappers.@declare_library_product(libcln, "@rpath/libcln.6.dylib")
JLLWrappers.@declare_executable_product(cln_pi)
function __init__()
    JLLWrappers.@generate_init_header(GMP_jll)
    JLLWrappers.@init_library_product(
        libcln,
        "lib/libcln.6.0.6.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        cln_pi,
        "bin/pi",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
